### PR TITLE
Various alignment and readability improvements.

### PR DESCRIPTION
**Pull request by BraininaBowl**

### CODE REVIEW

**Review by smcvb — APPROVED** [review]
Looks good to me :+1:

**Review by CodeDrivenMitch — CHANGES_REQUESTED** [review]
I tested the bundle out and found some problems with the new version.

The next/previous falls over the footer:
image

The footer no longer sticks to the bottom of the page:
image
And didn't we discuss to remove the black text completely from these pages?

**Comment by BraininaBowl** [comment]
@CodeDrivenMitch The footer shouldn't have been touched, I'll investigate.

The black text is added in https://github.com/AxonIQ/axoniq-library-site and requires some changes there.

**Comment by CodeDrivenMitch** [comment]
@BraininaBowl The black test is added in `partials/component-list|article.hbs`, the `dd` element there (`this.latest.asciidoc.attributes.component_description`)

**Review by CodeDrivenMitch — APPROVED** [review]
Looks a lot better, so I will approve it.

Just one nitty thing, the padding here seems very small:
image

It's on the Axon Framework Extensions page. We might want to give this a little bit more breathing room.

**Pull request merged**
