### PR TITLE
Header and footer tweaks

### PR DESCRIPTION
**Pull request by BraininaBowl**
- Added banner on top of header
- Changed header from Static to Sticky, for better flexibility
- Fixed footer alignment and spacing

### CODE REVIEW

**Review by smcvb — APPROVED** [review]
I trust in your judgment that this change is valid.

**Comment by CodeDrivenMitch** [comment]
There are still some problems with the sticky header.

Like in the following example, with code passing on top of it.
image

Text passes below the header, but it's still visible as well. 
image

**Comment by CodeDrivenMitch** [comment]
Maybe for a future PR, but shouldn't we hide this empty bar on the landing page?

image

Without anything, just the home icon, feels awkward to me. Just a suggestion.

**Comment by BraininaBowl** [comment]
@CodeDrivenMitch good catch. Please hold off on releasing this version, I'll put in a fix next year. Unless you get really bored over the holidays and feel the urge to pick this up.

About the bar: I think the empty bar still has value, showing the user where the breadcrumbs will be. Besides, the empty bar isn't entirely empty. There's still the actions menu on the right side. But I'll probably want to rework most of the breadcrumbs anyway, to make the structure more consistent.

**Pull request merged**
